spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url : jdbc:mariadb//localhost:3306/menudb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/menudb
    username : root
    password : 449966
#    fatal -> error-> warn -> info -> debug -> trace
#    fatal : ??????? ???? ?? ?? ??? ??
#    error : ?? ?? ? ?? ??
#    warn : ?? ????? ?? ??? ??? ?? ???
#    info : ???, ???? ?? ??? ???
#    debug : ?? ? ??? ??? ???? ???
#    trace : ??? ??? ???? ?? ? ? ??? ??
logging:
    level:
#      root: debug
      com:
        sumin:
          mybatisspring:
            section01:
              factorybean: debug